### ISSUE TITLE
Als klant wil ik een review bericht kunnen aanpassen zodat ik mogelijke fouten in het bericht kan herstellen

### ISSUE THREAD

**Issue by DaanMemelink** [hanaim-devops/devops-bp-pitstop-uitbreiding-team-tbd#9]
## Acceptatie criteria
Als er geen bericht of een te lang bericht wordt ingevoerd moet er een duidelijke foutmelding worden getoond
Als het reviewbericht is opgeslagen moet er een melding getoond worden

**Comment by MarkBijker** [comment]
Grotendeels af.
Er is alleen nog een bug met het versturen van de aangepaste review.

Issue is nu overgezet naar @luukjp aangezien hij dit nog nodig heeft voor zijn factsheet

**Comment by luukjp** [comment]
@MarkBijker zou je de bug kunnen toelichten?

**Comment by luukjp** [comment]
> [@MarkBijker](https://github.com/MarkBijker) zou je de bug kunnen toelichten?

Uitgelegd in discord:

Edit genereerde een 404 error.

**Comment by luukjp** [comment]
Na verdere onderzoek miste de ReviewerName in de post header & waren de HttpPost en HttpEdit tags incorrect ingesteld waardoor hij naar de verkeerde paths werd doorgelinked.
